"""Tests for IngestionPipeline and retrieve_from_silo."""
from __future__ import annotations

from unittest.mock import MagicMock, patch

import pytest

from api.core.ingestion_pipeline import IngestionPipeline
from api.core.myownclone.retrieval import retrieve_from_silo, RetrievalResult
from api.models.embedding_outbox import EmbeddingOutbox, OutboxStatus


# ---------- IngestionPipeline._chunk_text ----------


def test_chunk_short_text_returns_single_chunk():
    p = IngestionPipeline(chunk_size=100, chunk_overlap=20)
    chunks = p._chunk_text("short text")
    assert chunks == ["short text"]


def test_chunk_long_text_splits_with_overlap():
    p = IngestionPipeline(chunk_size=50, chunk_overlap=10)
    text = "a" * 200
    chunks = p._chunk_text(text)
    # Each chunk is 50 chars, step is 40, so we get 200/40 + 1 = 6 chunks
    assert len(chunks) > 1
    assert all(len(c) <= 50 for c in chunks)
    # Check overlap: last 10 chars of chunk N == first 10 of chunk N+1
    if len(chunks) >= 2:
        assert chunks[0][-10:] == chunks[1][:10]


def test_chunk_empty_returns_empty():
    p = IngestionPipeline()
    assert p._chunk_text("") == []


def test_chunk_skips_empty_chunks():
    p = IngestionPipeline(chunk_size=50, chunk_overlap=0)
    text = "a" * 50 + "   " + "b" * 50  # gap of whitespace between
    chunks = p._chunk_text(text)
    # The whitespace-only chunk should be skipped
    assert all(c.strip() for c in chunks)


# ---------- IngestionPipeline.ingest_chunks (with mocks) ----------


def test_ingest_chunks_writes_to_outbox():
    p = IngestionPipeline()
    mock_emb = MagicMock()
    mock_emb.embed_texts.return_value = [[0.1, 0.2], [0.3, 0.4]]

    # Mock db session
    mock_session = MagicMock()
    with patch.object(p, "embedding_service", mock_emb), \
         patch("api.core.ingestion_pipeline.db.session", mock_session):
        chunk_ids = p.ingest_chunks("tenant-1", ["hello", "world"])

    # 2 chunks → 2 outbox IDs returned (real UUIDs generated by the model)
    assert len(chunk_ids) == 2
    assert all(isinstance(cid, str) and len(cid) == 36 for cid in chunk_ids)
    mock_emb.embed_texts.assert_called_once_with("tenant-1", ["hello", "world"])
    assert mock_session.add.call_count == 2
    mock_session.commit.assert_called_once()


def test_ingest_chunks_empty_returns_empty():
    p = IngestionPipeline()
    assert p.ingest_chunks("tenant-1", []) == []


def test_ingest_text_chunks_then_embeds():
    p = IngestionPipeline(chunk_size=20, chunk_overlap=5)
    mock_emb = MagicMock()
    mock_emb.embed_texts.return_value = [[0.1] * 1536, [0.2] * 1536, [0.3] * 1536, [0.4] * 1536]
    with patch.object(p, "embedding_service", mock_emb), \
         patch("api.core.ingestion_pipeline.db.session", MagicMock()):
        chunk_ids = p.ingest_text("tenant-1", "a" * 50)

    # With chunk_size=20, overlap=5: step=15. "a"*50 gives 4 chunks at positions 0,15,30,45
    # (45: only 5 chars remain but still non-empty after strip)
    assert len(chunk_ids) == 4
    mock_emb.embed_texts.assert_called_once()


# ---------- retrieve_from_silo ----------


def test_retrieve_empty_query_returns_empty():
    result = retrieve_from_silo("tenant-1", "")
    assert result.found is False
    assert result.contents == []


def test_retrieve_whitespace_query_returns_empty():
    result = retrieve_from_silo("tenant-1", "   ")
    assert result.found is False


def test_retrieve_no_weaviate_client_returns_empty():
    """Without a Weaviate client, return empty (caller can fall back)."""
    mock_emb = MagicMock()
    mock_emb.embed_texts.return_value = [[0.1, 0.2]]
    with patch("api.core.myownclone.retrieval.EmbeddingService", return_value=mock_emb):
        result = retrieve_from_silo("tenant-1", "query", weaviate_client=None)
    assert result.found is False


def test_retrieve_embedding_failure_returns_empty():
    mock_emb = MagicMock()
    mock_emb.embed_texts.side_effect = RuntimeError("embed failed")
    with patch("api.core.myownclone.retrieval.EmbeddingService", return_value=mock_emb):
        result = retrieve_from_silo("tenant-1", "query", weaviate_client=None)
    assert result.found is False


def test_retrieve_with_mocked_weaviate_returns_results():
    """Mock a Weaviate response and verify parsing."""
    mock_emb = MagicMock()
    mock_emb.embed_texts.return_value = [[0.1, 0.2]]

    # Mock Weaviate collection response
    mock_obj1 = MagicMock()
    mock_obj1.properties = {"text": "first result"}
    mock_obj1.metadata.distance = 0.1
    mock_obj1.uuid = "uuid-1"

    mock_obj2 = MagicMock()
    mock_obj2.properties = {"text": "second result"}
    mock_obj2.metadata.distance = 0.2
    mock_obj2.uuid = "uuid-2"

    mock_response = MagicMock()
    mock_response.objects = [mock_obj1, mock_obj2]

    mock_collection = MagicMock()
    mock_collection.query.near_vector.return_value = mock_response

    mock_client = MagicMock()
    mock_client.collections.get.return_value = mock_collection

    with patch("api.core.myownclone.retrieval.EmbeddingService", return_value=mock_emb):
        result = retrieve_from_silo("tenant-1", "query", weaviate_client=mock_client, top_k=2)

    assert result.found is True
    assert result.contents == ["first result", "second result"]
    # Distance 0.1 → similarity 0.9, distance 0.2 → similarity 0.8
    assert result.scores == [0.9, 0.8]
    assert result.chunk_ids == ["uuid-1", "uuid-2"]


def test_retrieve_dim_mismatch_logs_warning_but_continues():
    """If dimension guard fails, log warning and still attempt search."""
    mock_emb = MagicMock()
    mock_emb.embed_texts.return_value = [[0.1, 0.2]]

    mock_response = MagicMock()
    mock_response.objects = []

    mock_collection = MagicMock()
    mock_collection.query.near_vector.return_value = mock_response

    mock_client = MagicMock()
    mock_client.collections.get.return_value = mock_collection
    # Simulate dimension mismatch
    mock_client.schema.get.return_value = {"vectorIndexConfig": {"size": 768}}  # mismatch

    with patch("api.core.myownclone.retrieval.EmbeddingService", return_value=mock_emb):
        # Should not raise; should log warning
        result = retrieve_from_silo(
            "tenant-1", "query", weaviate_client=mock_client, expected_embedding_dim=1536
        )
    assert result.found is False  # no objects