CREATE INDEX "analytics_gaps_clone_id_idx" ON "analytics_gaps" USING btree ("clone_id");--> statement-breakpoint
CREATE INDEX "analytics_questions_clone_id_idx" ON "analytics_questions" USING btree ("clone_id");--> statement-breakpoint
CREATE INDEX "availability_clone_id_idx" ON "availability" USING btree ("clone_id");--> statement-breakpoint
CREATE INDEX "availability_clone_day_idx" ON "availability" USING btree ("clone_id","day_of_week");--> statement-breakpoint
CREATE INDEX "bookings_meeting_type_id_idx" ON "bookings" USING btree ("meeting_type_id");--> statement-breakpoint
CREATE INDEX "bookings_meeting_date_idx" ON "bookings" USING btree ("meeting_type_id","date");--> statement-breakpoint
CREATE INDEX "bookings_status_idx" ON "bookings" USING btree ("status");--> statement-breakpoint
CREATE INDEX "chunks_source_id_idx" ON "chunks" USING btree ("source_id");--> statement-breakpoint
CREATE INDEX "clone_configs_tenant_id_idx" ON "clone_configs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "clone_configs_is_active_idx" ON "clone_configs" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "clone_mode_prompts_clone_id_idx" ON "clone_mode_prompts" USING btree ("clone_id");--> statement-breakpoint
CREATE INDEX "conversations_clone_id_idx" ON "conversations" USING btree ("clone_id");--> statement-breakpoint
CREATE INDEX "conversations_visitor_id_idx" ON "conversations" USING btree ("visitor_id");--> statement-breakpoint
CREATE INDEX "emails_clone_id_idx" ON "emails" USING btree ("clone_id");--> statement-breakpoint
CREATE INDEX "emails_status_idx" ON "emails" USING btree ("status");--> statement-breakpoint
CREATE INDEX "emails_thread_id_idx" ON "emails" USING btree ("thread_id");--> statement-breakpoint
CREATE INDEX "meeting_types_clone_id_idx" ON "meeting_types" USING btree ("clone_id");--> statement-breakpoint
CREATE INDEX "meeting_types_active_idx" ON "meeting_types" USING btree ("active");--> statement-breakpoint
CREATE INDEX "memories_clone_id_idx" ON "memories" USING btree ("clone_id");--> statement-breakpoint
CREATE INDEX "memories_clone_type_idx" ON "memories" USING btree ("clone_id","type");--> statement-breakpoint
CREATE INDEX "messages_conversation_id_idx" ON "messages" USING btree ("conversation_id");--> statement-breakpoint
CREATE INDEX "products_clone_id_idx" ON "products" USING btree ("clone_id");--> statement-breakpoint
CREATE INDEX "products_status_idx" ON "products" USING btree ("status");--> statement-breakpoint
CREATE INDEX "sources_clone_id_idx" ON "sources" USING btree ("clone_id");--> statement-breakpoint
CREATE INDEX "sources_status_idx" ON "sources" USING btree ("status");--> statement-breakpoint
CREATE INDEX "tenants_status_idx" ON "tenants" USING btree ("status");--> statement-breakpoint
CREATE INDEX "tenants_subscription_status_idx" ON "tenants" USING btree ("subscription_status");--> statement-breakpoint
CREATE INDEX "users_tenant_id_idx" ON "users" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "users_role_idx" ON "users" USING btree ("role");--> statement-breakpoint
CREATE INDEX "users_platform_admin_idx" ON "users" USING btree ("is_platform_admin");