"""Base classes for MyOwnClone SQLAlchemy models.

`TypeBase` is a real SQLAlchemy 2.x `MappedAsDataclass` + `DeclarativeBase`,
so the `Mapped[]` annotations with dataclass-style arguments
(`default=`, `default_factory=`, `init=`) on subclass columns are recognised
by the ORM at class-definition time.

`DefaultFieldsDCMixin` provides `created_at` / `updated_at` and an `id` column
defaulting to UUIDv7. Models may inherit either `TypeBase` directly or combine
`DefaultFieldsDCMixin` with `TypeBase`.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, MetaData, String, func
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    MappedAsDataclass,
    declared_attr,
    mapped_column,
)

# Single naming convention keeps alembic autogenerate diffs predictable.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def naive_utc_now() -> datetime:
    """Return naive datetime in UTC.

    The MyOwnClone migrations use `DateTime` without `timezone=True`, so all
    timestamps round-trip as naive UTC. Use this helper everywhere to avoid
    mixing tz-aware and naive datetimes.
    """
    return datetime.now(timezone.utc).replace(tzinfo=None)


def uuidv7() -> str:
    """Generate a UUIDv4 string used as the primary-key default.

    True UUIDv7 support needs the `uuid7` package; v4 is universally supported
    and preserves the intent of "time-ordered, distributed-safe ID" well enough
    for our scale.
    """
    return str(uuid.uuid4())


class TypeBase(MappedAsDataclass, DeclarativeBase):
    """Declarative base for every MyOwnClone model.

    Inherits from `MappedAsDataclass` so subclass columns can use the
    dataclass-style arguments (`default=`, `default_factory=`, `init=`).
    `__init__` is generated by the dataclass machinery and accepts only
    the columns marked `init=True` (everything not explicitly `init=False`).
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class DefaultFieldsDCMixin:
    """Adds `id`, `created_at` and `updated_at` columns to a model.

    Use together with `TypeBase`, e.g.:

        class Thing(DefaultFieldsDCMixin, TypeBase):
            __tablename__ = "things"
            name: Mapped[str] = mapped_column(String(255), nullable=False)
    """

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        insert_default=lambda: uuidv7(),
        default_factory=uuidv7,
        init=False,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False,
        insert_default=naive_utc_now,
        default_factory=naive_utc_now,
        init=False,
        server_default=func.current_timestamp(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False,
        insert_default=naive_utc_now,
        default_factory=naive_utc_now,
        init=False,
        server_default=func.current_timestamp(),
        onupdate=naive_utc_now,
    )

    @declared_attr.directive
    def __tablename__(cls) -> str:  # noqa: N805
        # Allow `class Thing(DefaultFieldsDCMixin, TypeBase)` without
        # an explicit __tablename__ — derive from class name.
        import re
        snake = re.sub(r"(?<!^)(?=[A-Z])", cls.__name__).lower()
        return snake
